name: earthquake-producer
language: python
variables:
  - name: KAFKA_TOPIC
    inputType: OutputTopic
    description: Topic where we save the processed earthquake data
    defaultValue: earthquake
    required: true
  - name: LIVE_OR_HISTORICAL
    inputType: FreeText
    description: Whether we choose live or historical data
    defaultValue: live
    required: true
dockerfile: Dockerfile
runEntryPoint: src/main.py
defaultFile: src/main.py
