name: earthquake_aggregator
language: python
variables:
  - name: INPUT_TOPIC
    inputType: InputTopic
    description: Topic containing raw earthquake data
    defaultValue: earthquake
    required: true
  - name: KAFKA_OUTPUT_TOPIC
    inputType: OutputTopic
    description: Earthquakes aggregated by a specified tumbling window
    defaultValue: earthquake_aggregated
    required: true
dockerfile: Dockerfile
runEntryPoint: src/main.py
defaultFile: src/main.py
