name: earthquake_aggregator
language: python
variables:
  - name: INPUT_TOPIC
    inputType: InputTopic
    description: Topic containing raw earthquake data
    defaultValue: earthquake
    required: true
  - name: OUTPUT_TOPIC
    inputType: OutputTopic
    description: Earthquakes aggregated by a specified tumbling window
    defaultValue: earthquake_aggregated
    required: true
  - name: WINDOW_DURATION_SECONDS
    inputType: FreeText
    description: Duration of the tumbling window
    defaultValue: 3600
    required: true
  - name: kafka_consumer_group
    inputType: FreeText
    description: Consumer group to consume data from the input topic
    defaultValue: earthquake_aggregated_consumer_group
    required: true
dockerfile: Dockerfile
runEntryPoint: src/main.py
defaultFile: src/main.py
