name: kafka-to-feature-store
language: python
variables:
  - name: KAFKA_TOPIC
    inputType: InputTopic
    description: Topic containing earthquake data
    defaultValue: earthquake
    required: true
dockerfile: Dockerfile
runEntryPoint: src/main.py
defaultFile: src/main.py
