name: kafka-to-feature-store
language: python
variables:
  - name: KAFKA_TOPIC
    inputType: InputTopic
    description: Topic containing earthquake data
    defaultValue: earthquake
    required: true
  - name: KAFKA_CONSUMER_GROUP
    inputType: FreeText
    description: Consumer that reads data from the KAFKA_TOPIC
    defaultValue: earthquake_consumer_group
    required: true
  - name: FEATURE_GROUP_NAME
    inputType: FreeText
    description: Name of the Hopsworks feature group to write data to
    defaultValue: earthquakes
    required: true
  - name: FEATURE_GROUP_VERSION
    inputType: FreeText
    description: Version of the Hopsworks feature group to write data to
    defaultValue: 1
    required: true
  - name: BUFFER_SIZE
    inputType: FreeText
    description: Size of the buffer to push to the feature store
    defaultValue: 1
    required: true
  - name: LIVE_OR_HISTORICAL
    inputType: FreeText
    description: Live if we run using realtime data, historical otherwise
    defaultValue: live
    required: true
  - name: HOPSWORKS_API_KEY
    inputType: Secret
    description: API key to connect to Hopsworks
    defaultValue: HOPSWORKS_API_KEY
    required: true
  - name: HOPSWORKS_PROJECT_NAME
    inputType: Secret
    description: Hopsworks Project where our feature store is
    defaultValue: HOPSWORKS_PROJECT_NAME
    required: true
  - name: SAVE_EVERY_N_SEC
    inputType: FreeText
    description: Time before buffer is pushed to feature store
    defaultValue: 600
    required: true
dockerfile: Dockerfile
runEntryPoint: src/main.py
defaultFile: src/main.py
