name: earthquake-producer
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write to.
    defaultValue: transform
    required: false
dockerfile: Dockerfile
runEntryPoint: main.py
defaultFile: main.py
