name: earthquake-producer
language: python
variables:
  - name: KAFKA_TOPIC
    inputType: OutputTopic
    description: Topic where we save the processed earthquake data
    defaultValue: earthquake
    required: true
dockerfile: Dockerfile
runEntryPoint: main.py
defaultFile: main.py
