train-dev:
	source ../../setup_credentials.sh && \
	source setup_config.sh && \
	poetry run python src/training.py

training-data-dev:
	source ../../setup_credentials.sh && \
	source setup_config.sh && \
	poetry run python src/training_data.py
